### ISSUE TITLE
Web site not published

### ISSUE THREAD

**Issue by tfmorris** [Early-Modern-OCR/early-modern-ocr.github.io#1]
This web site doesn't actually appear to be published on github.io, causing all of the links to it in the final report PDF to be dead.

**Comment by mchristy-tamu** [comment]
Hi Tom,

Thanks for letting us know. I'm investigating now.

Matt Christy

**Comment by mchristy-tamu** [comment]
Hi Tom,

I honestly don't know what the problem is and why it stopped working. Everything looks right. Google isn't helping me so far either. I'm still trying to figure it out. In the meantime, please use this page as an alternative: http://emop.tamu.edu/outcomes/github.

Thanks,
Matt Christy

**Comment by mchristy-tamu** [comment]
Hi Tom,

OK. The problem is that the link should have had an https prefix. I see it on some of the links in the doc, but not all. I'll have to go in and edit that. Sorry for the hassle, and thanks again for letting us know about this problem.

Matt Christy

**Comment by tfmorris** [comment]
Cool.  Thanks for the quick fix!
